[tool.poetry]
name = "day25"
version = "0.1.0"
description = ""
authors = ["Rayshard Thompson <rayshard.t123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
networkx = "^3.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
